language: elixir
elixir:
  - 1.8.2
otp_release:
  - 21.0
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: code quality
      script: mix test
    - stage: code quality
      script: mix credo