language: elixir
elixir:
  - 1.11
otp_release:
  - 22.0
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: code quality
      script:
        - mix test
    - stage: code quality
      script:
        - mix credo
