language: elixir
elixir:
  - 1.6
otp_release:
  - 20.0
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: code quality
      script:
        - mix test
    - stage: code quality
      script:
        - MIX_ENV=test mix coveralls.json -u
        - bash <(curl -s https://codecov.io/bash)
    - stage: code quality
      script:
        - mix credo
    - stage: code quality
      script:
        - mix dialyzer
    - stage: code quality
      script:
        - mix inch
        - mix inch.report
    - stage: deploy to gigalixir
      # if: branch = master
      script:
        - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
        - git push -f gigalixir HEAD:refs/heads/master
    - stage: verify deployment
      script: 'curl -f https://ss.gigalixirapp.com'
