use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# SentientSocialWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.

# Heroku config
# config :sentient_social_web, SentientSocialWeb.Endpoint,
#   load_from_system_env: true,
#   url: [scheme: "https", host: "#{System.get_env("APP_NAME")}.herokuapp.com", port: 443],
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   cache_static_manifest: "priv/static/cache_manifest.json",
#   secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

# Gigalixir config
# config :sentient_social_web, SentientSocialWeb.Endpoint,
#  load_from_system_env: true,
#  server: true,
#  secret_key_base: "${SECRET_KEY_BASE}",
#  url: [host: "sentientsocial.io", port: 443],
#  cache_static_manifest: "priv/static/cache_manifest.json"

# PCF config
config :sentient_social_web, SentientSocialWeb.Endpoint,
  http: [:inet4, port: System.get_env("PORT") || 4000],
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  debug_errors: true,
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

secret_key_base = System.get_env("SECRET_KEY_BASE") || raise "SECRET_KEY_BASE must be set"
config :sentient_social_web, SentientSocialWeb.Endpoint, secret_key_base: secret_key_base

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :sentient_social_web, SentientSocialWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :sentient_social_web, SentientSocialWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :sentient_social_web, SentientSocialWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
